// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz1CwivGOdpdVcDr6b40Ecg7k2HWt453o',
    appId: '1:1061874818606:web:4c2b396539594b8dbbc9bf',
    messagingSenderId: '1061874818606',
    projectId: 'iti-training-244ec',
    authDomain: 'iti-training-244ec.firebaseapp.com',
    storageBucket: 'iti-training-244ec.appspot.com',
    measurementId: 'G-VD6EPSS0DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmklqv5czImE85jwqrNaNsrzd_dGIu3NA',
    appId: '1:1061874818606:android:aed0b68df08363bbbbc9bf',
    messagingSenderId: '1061874818606',
    projectId: 'iti-training-244ec',
    storageBucket: 'iti-training-244ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5lHKQbtJQ8sQYkulUdHaQbS--KLxrn3c',
    appId: '1:1061874818606:ios:174062a4dc36c02abbc9bf',
    messagingSenderId: '1061874818606',
    projectId: 'iti-training-244ec',
    storageBucket: 'iti-training-244ec.appspot.com',
    iosClientId: '1061874818606-t503k31fnphgnilg2s2ms14b0sdr2odo.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab4',
  );
}
